name: geofencing-viewer
dependencies:
  - python
  - pytest
  - pytest-cov
  - pyyaml
  - pip:
    - gevent
    - gevent-websocket
    - gunicorn
    - flask-socketio
    - websockets
    - geojson
    - git+https://git@github.com/eurocontrol-swim/geofencing-service-client.git
    - git+https://git@github.com/eurocontrol-swim/rest-client.git
    - git+https://git@github.com/eurocontrol-swim/swim-qpid-proton.git
    - git+https://git@github.com/eurocontrol-swim/pubsub-facades.git
    - git+https://git@github.com/eurocontrol-swim/swim-backend.git
    - python-qpid_proton
