name: geofencing-viewer
dependencies:
  - python
  - pytest
  - pytest-cov
  - pyyaml
  - Flask
  - python-dateutil
  - pip:
    - gunicorn
    - geojson
    - git+https://git@github.com/eurocontrol-swim/geofencing-service-client.git
    - git+https://git@github.com/eurocontrol-swim/rest-client.git
    - git+https://git@github.com/eurocontrol-swim/swim-qpid-proton.git
    - git+https://git@github.com/eurocontrol-swim/pubsub-facades.git
    - git+https://git@github.com/eurocontrol-swim/swim-backend.git
    - python-qpid_proton
