LOGGING:
  version: 1

  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      level: DEBUG

  formatters:
    default:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      class: logging.Formatter

  disable_existing_loggers: false

  root:
    level: DEBUG
    handlers: [console]

  loggers:

    geofencing_viewer:
      level: INFO

    proton:
      level: INFO

    geventwebsocket.handler:
      level: INFO

BROKER:
  host: '0.0.0.0:5671'
  cert_db: '/secrets/rabbitmq/ca_certificate.pem'
  sasl_user: 'swim-explorer-broker'
  sasl_password: 'swim-secret'

# Geofencing service
SUBSCRIPTION-MANAGER-API:
  host: 'localhost:8000'
  https: false
  timeout: 30
  verify: false
  username: geofencing-viewer
  password: geofencing-viewer


INITIAL_UAS_ZONES_FILTER:
  airspaceVolume:
    horizontalProjection:
      type: 'Polygon'
      coordinates: [[
        [4.371125, 50.901767],
        [4.224330, 50.866953],
        [4.342881, 50.788595],
        [4.535647, 50.846430],
        [4.371125, 50.901767]
      ]]
    uomDimensions: 'M'
    lowerLimit: 0
    upperLimit: 100000
    upperVerticalReference: 'AMSL'
    lowerVerticalReference: 'AMSL'
  startDateTime: '2020-01-01T00:00:00+01:00'
  endDateTime: '2021-01-01T00:00:00+01:00'
  regions:
    - 1

POLLING_INTERVAL_IN_SEC: 1
