LOGGING:
  version: 1

  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      level: DEBUG

  formatters:
    default:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      class: logging.Formatter

  disable_existing_loggers: false

  root:
    level: DEBUG
    handlers: [console]

  loggers:
    swim-pubsub:
      level: DEBUG

    proton:
      level: INFO

    geventwebsocket.handler:
      level: INFO

BROKER:
  host: '0.0.0.0:5671'
  cert_db: '/secrets/rabbitmq/ca_certificate.pem'
  sasl_user: 'ny-consumer'
  sasl_password: 'ny'

# Geofencing service
SUBSCRIPTION-MANAGER-API:
  host: 'localhost:8000'
  https: false
  timeout: 30
  verify: false
  username: 'geofencing'
  password: 'geofencing'


GEOFENCING_VIEWER_GS_USER: 'geofencing'
GEOFENCING_VIEWER_GS_PASS: 'geofencing'
